services:
  postgres-orders:
    image: postgres:15-alpine
    container_name: service-db
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: order_migration
    ports:
      - "5432:5432"
    volumes:
      - ./scenario/current/schema.sql:/docker-entrypoint-initdb.d/01.schema.sql
      - ./scenario/sample-data.sql:/docker-entrypoint-initdb.d/02.sample-data.sql
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: migration-network